import { X, Download, FileText, TrendingUp, TrendingDown } from 'lucide-react'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable' // <-- CHANGED: Import autoTable function

export default function WeeklyReportModal({ user, transactions, onClose }) {
  
  // Calculate Report Data
  const income = transactions
    .filter(t => (t.type || '').toLowerCase() === 'income')
    .reduce((sum, t) => sum + Number(t.amount), 0)

  const expense = transactions
    .filter(t => (t.type || '').toLowerCase() === 'expense')
    .reduce((sum, t) => sum + Number(t.amount), 0)

  const savings = income - expense
  const savingsRate = income > 0 ? ((savings / income) * 100).toFixed(1) : 0

  // Get Top Expense Category
  const catTotals = transactions
    .filter(t => (t.type || '').toLowerCase() === 'expense')
    .reduce((acc, t) => {
      acc[t.category] = (acc[t.category] || 0) + Number(t.amount)
      return acc
    }, {})
  
  const topCategory = Object.entries(catTotals).sort((a, b) => b[1] - a[1])[0] || ['None', 0]

  // PDF Generator Function
  const handleDownloadPDF = () => {
    const doc = new jsPDF()
    
    // Brand Colors
    const primaryColor = [0, 188, 212] 
    const secondaryColor = [14, 116, 144]

    // Header
    doc.setFillColor(...primaryColor)
    doc.rect(0, 0, 210, 40, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(22)
    doc.text("Spennies Weekly Report", 14, 25)
    doc.setFontSize(10)
    doc.text(`Generated for: ${user.name}`, 14, 32)
    doc.text(`${new Date().toLocaleDateString()}`, 180, 25, { align: 'right' })

    // Summary Cards
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(14)
    doc.text("Financial Summary", 14, 55)

    // CORRECTION 1: Changed doc.autoTable to autoTable(doc, ...)
    autoTable(doc, { 
      startY: 60,
      head: [['Total Income', 'Total Expenses', 'Net Savings', 'Savings Rate']],
      body: [[`Rs ${income}`, `Rs ${expense}`, `Rs ${savings}`, `${savingsRate}%`]],
      theme: 'grid',
      headStyles: { fillColor: secondaryColor, halign: 'center' },
      bodyStyles: { halign: 'center', fontSize: 12 }
    })

    // Insights
    doc.text("Key Insights", 14, 90)
    doc.setFontSize(10)
    doc.setTextColor(100)
    doc.text(`• Biggest Spending Category: ${topCategory[0]} (Rs ${topCategory[1]})`, 14, 100)
    doc.text(`• Transaction Count: ${transactions.length} transactions recorded`, 14, 106)
    if (savings < 0) doc.text(`• Warning: Expenses exceeded income this period.`, 14, 112)
    else doc.text(`• Great job! You saved ${savingsRate}% of your income.`, 14, 112)

    // Transaction Table
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(14)
    doc.text("Transaction Details", 14, 125)

    const tableRows = transactions.map(t => [
      new Date(t.date).toLocaleDateString(),
      t.category,
      t.description,
      t.type.toUpperCase(),
      `Rs ${t.amount}`
    ])

    // CORRECTION 2: Changed doc.autoTable to autoTable(doc, ...)
    autoTable(doc, {
      startY: 130,
      head: [['Date', 'Category', 'Description', 'Type', 'Amount']],
      body: tableRows,
      theme: 'striped',
      styles: { fontSize: 9 },
      headStyles: { fillColor: [100, 100, 100] }
    })

    // Footer
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text('Generated by Spennies AI - Your Financial Companion', 105, 290, { align: 'center' })

    doc.save(`Spennies_Report_${new Date().toISOString().split('T')[0]}.pdf`)
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto shadow-2xl animate-fade-in-up">
        
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-100 sticky top-0 bg-white z-10">
          <div className="flex items-center gap-3">
            <div className="bg-primary/10 p-2 rounded-full">
              <FileText className="w-6 h-6 text-primary" />
            </div>
            <div>
              <h3 className="text-xl font-bold text-gray-800">Weekly Analysis</h3>
              <p className="text-xs text-gray-500">Preview & Download</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-full transition-colors">
            <X className="w-6 h-6 text-gray-500" />
          </button>
        </div>

        {/* Preview Content (HTML Representation of PDF) */}
        <div className="p-6 space-y-6">
          
          {/* Summary Section */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="p-4 bg-green-50 rounded-xl border border-green-100">
              <p className="text-xs text-green-600 font-medium uppercase">Income</p>
              <p className="text-xl font-bold text-green-800">₹{income.toLocaleString()}</p>
            </div>
            <div className="p-4 bg-red-50 rounded-xl border border-red-100">
              <p className="text-xs text-red-600 font-medium uppercase">Expenses</p>
              <p className="text-xl font-bold text-red-800">₹{expense.toLocaleString()}</p>
            </div>
            <div className="p-4 bg-blue-50 rounded-xl border border-blue-100">
              <p className="text-xs text-blue-600 font-medium uppercase">Savings</p>
              <p className="text-xl font-bold text-blue-800">₹{savings.toLocaleString()}</p>
            </div>
            <div className="p-4 bg-purple-50 rounded-xl border border-purple-100">
              <p className="text-xs text-purple-600 font-medium uppercase">Rate</p>
              <p className="text-xl font-bold text-purple-800">{savingsRate}%</p>
            </div>
          </div>

          {/* Insights Preview */}
          <div className="bg-gray-50 p-5 rounded-xl border border-gray-200">
            <h4 className="font-bold text-gray-700 mb-3 flex items-center gap-2">
              <TrendingUp className="w-4 h-4" /> Key Insights
            </h4>
            <ul className="space-y-2 text-sm text-gray-600">
              <li className="flex items-start gap-2">
                <span className="text-primary">•</span>
                Top Spending Category: <strong>{topCategory[0]}</strong> (₹{topCategory[1]})
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary">•</span>
                Total Transactions: {transactions.length}
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary">•</span>
                {savings >= 0 ? "You are cash-flow positive this week! 🎉" : "Warning: Expenses exceeded income 📉"}
              </li>
            </ul>
          </div>

          {/* Transaction Table Preview */}
          <div>
            <h4 className="font-bold text-gray-700 mb-3">Transaction Details</h4>
            <div className="overflow-x-auto border border-gray-200 rounded-lg">
              <table className="w-full text-sm text-left">
                <thead className="bg-gray-50 text-gray-500 font-medium">
                  <tr>
                    <th className="px-4 py-3">Date</th>
                    <th className="px-4 py-3">Description</th>
                    <th className="px-4 py-3 text-right">Amount</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {transactions.slice(0, 5).map((t, i) => (
                    <tr key={i} className="hover:bg-gray-50/50">
                      <td className="px-4 py-3">{new Date(t.date).toLocaleDateString()}</td>
                      <td className="px-4 py-3">
                        <div className="font-medium text-gray-800">{t.description}</div>
                        <div className="text-xs text-gray-500">{t.category}</div>
                      </td>
                      <td className={`px-4 py-3 text-right font-bold ${t.type.toLowerCase() === 'income' ? 'text-green-600' : 'text-red-600'}`}>
                        {t.type.toLowerCase() === 'income' ? '+' : '-'}₹{t.amount}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              {transactions.length > 5 && (
                <div className="p-3 text-center text-xs text-gray-500 bg-gray-50 border-t border-gray-100">
                  + {transactions.length - 5} more rows in full PDF
                </div>
              )}
            </div>
          </div>

        </div>

        {/* Footer Actions */}
        <div className="p-6 border-t border-gray-100 bg-gray-50/50 flex gap-4">
          <button 
            onClick={onClose}
            className="flex-1 py-3 px-4 bg-white border border-gray-300 text-gray-700 rounded-xl font-medium hover:bg-gray-50 transition-colors"
          >
            Close
          </button>
          <button 
            onClick={handleDownloadPDF}
            className="flex-1 py-3 px-4 bg-primary text-white rounded-xl font-medium shadow-lg shadow-primary/30 hover:bg-secondary transition-all flex items-center justify-center gap-2"
          >
            <Download className="w-5 h-5" /> Download PDF
          </button>
        </div>

      </div>
    </div>
  )
}